### ISSUE TITLE
fromGeoJson() truncates property names to 8 characters

### ISSUE THREAD

**Issue by davidbeers** [haoliangyu/gtran-shapefile#2]
Although the SHP spec permits attribute names up to 10 characters in length (see https://en.wikipedia.org/wiki/Shapefile#Data_storage) the conversion from GeoJSON to SHP truncates them to 8 characters.

**Comment by haoliangyu** [comment]
This is unfortunately an issue of the dependency `shp-write`. See https://github.com/mapbox/shp-write/issues/74

**Comment by davidbeers** [comment]
Thanks, I'm chiming in on the shp-write issue.

**Comment by haoliangyu** [comment]
Also see https://github.com/mapbox/dbf/pull/33

**Comment by sheindel** [comment]
Hello! I'm not sure if this repo is still used/maintained, but we have finally resurrected both `dbf` and `shp-write` to resolve some of these long standing issues. Feel free to update the dependency if you see some value in it. The API should have remained the same (with a few improvements) but you may want to specify the `outputType` and the `compression` types in your call `shp-write`

**Comment by sheindel** [comment]
Please note that the package has changed from `shp-write` to `@mapbox/shp-write` due to changes in mapbox package organization

**Comment by haoliangyu** [comment]
@sheindel Thanks for reminding me of the update. This issue is addressed at v1.1.6.
